name: lua-format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: xmake-io/github-action-setup-xmake@v1
    - run: |
        xmake repo --update
        xmake build test
        xmake run test
